k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: default
  clusters:
  thresholds:
    cpu:
      critical: 90
      warn: 85
    memory:
      critical: 90
      warn: 85
