k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 5000
    buffer: 50000
    sinceSeconds: 0
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext:
  currentCluster:
  clusters: []
  thresholds:
    cpu:
      critical: 90
      warn: 80
    memory:
      critical: 90
      warn: 80
