k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: admin@clusterfun-scaleway
  currentCluster: clusterfun-scaleway
  clusters:
    clusterfun-scaleway:
      namespace:
        active: nextcloud
        favorites:
        - cv
        - logging
        - node-red
        - gitea
        - all
        - kube-system
        - nextcloud
        - chat
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    microk8s-cluster:
      namespace:
        active: ""
        favorites:
        - ingress
        - kube-system
        - argocd
        - logging
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
