#!/usr/bin/env bash

set -e

echo "⬆️  Updating tools ⬆️"
echo

if which opsctl &>/dev/null ; then
  printf "⏳ opsctl..."
  opsctl version update --no-cache 1>/dev/null
  printf "\n\e[1A\e[K✅ opsctl - %s\n" $(opsctl version | grep "^Version:" | awk -F' ' '{print $NF}')
fi

if which devctl &>/dev/null ; then
  printf "⏳ devctl... "
  devctl version update --no-cache 1>/dev/null
  printf "\n\e[1A\e[K✅ devctl - %s\n" $(devctl version | grep "^Version:" | awk -F' ' '{print $NF}')
fi

if which kubectl-gs &>/dev/null ; then
  printf "⏳ kubectl-gs... "
  kubectl-gs selfupdate 1>/dev/null
  printf "\n\e[1A\e[K✅ kubectl-gs - %s\n" $(kubectl-gs --version | awk -F' ' '{print $NF}')
fi
