prompt_order=["directory","git_branch","git_commit","git_state","git_status","package","golang","nodejs","terraform","memory_usage","aws","kubernetes","cmd_duration","custom","line_break","jobs","battery","time","character"]

[character]
symbol = "✨ "
error_symbol = "✗ "
use_symbol_for_status = true
style_success = "yellow"

[aws]
symbol = " "
displayed_items = "profile"

[docker]
symbol = " "

[git_commit]
only_detached = true
prefix = "(#"

[golang]
symbol = " "

[kubernetes]
symbol = "ﴱ "
style = "bold blue"
disabled = false

[terraform]
show_version = true

[nodejs]
symbol = " "
