version: 3
profiles: []
hotkeys:
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  duplicate-tab: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  toggle-window: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Desert
    foreground: '#ffffff'
    background: '#333333'
    cursor: '#00ff00'
    colors:
      - '#4d4d4d'
      - '#ff2b2b'
      - '#98fb98'
      - '#f0e68c'
      - '#cd853f'
      - '#ffdead'
      - '#ffa0a0'
      - '#f5deb3'
      - '#555555'
      - '#ff5555'
      - '#55ff55'
      - '#ffff55'
      - '#87ceff'
      - '#ff55ff'
      - '#ffd700'
      - '#ffffff'
  font: OpenDyslexicMono Nerd Font
  ligatures: true
  cursor: beam
  pasteOnMiddleClick: false
  autoOpen: true
  customColorSchemes: []
  background: colorScheme
ssh: {}
configSync:
  parts: {}
clickableLinks:
  modifier: metaKey
appearance:
  dockFill: 0.23
  css: ''
pluginBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
profileDefaults: {}
recoverTabs: false
electronFlags:
  - - force_discrete_gpu
    - '0'
